version: "3"
services:
  resource-server:
    image: minudev1212/withkid-resource-server:0.6.1
    deploy:
      replicas: 5
      resources: 
        limits:
          cpus: "0.1"
          memory: 50M
    ports: 
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - withkid-bridge
  auth-server:
    image: minudev1212/withkid-auth-server:0.4.1
    deploy:
      replicas: 5
      resources: 
        limits:
          cpus: "0.1"
          memory: 50M
    ports: 
      - "8090:8082"
    expose: 
      - "8082"
    networks:
      - withkid-bridge
networks:
  withkid-bridge: 
    external: true

