version: "3"
services:
  resource-server:
    image: minudev1212/withkid-resource-server:0.6.1
    ports: 
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - withkid_bridge
  auth-server:
    image: minudev1212/withkid-auth-server:0.4.1
    ports: 
      - "8090:8082"
    expose: 
      - "8082"
    networks:
      - withkid_bridge
networks:
  withkid_bridge: 
    external: true

