version: "3"

services:
  resource_server:
    image: minudev1212/withkid-resource-server:0.6.3
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 200M
      restart_policy:
        condition: on-failure
    depends_on:
      - rdb
      - redis
    ports:
      - "8081:8081"
    networks:
      - overlay
  auth_server:
    image: minudev1212/withkid-auth-server:0.4.3
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 200M
      restart_policy:
        condition: on-failure
    depends_on:
      - rdb
      - nginx
    networks:
      - overlay

  rdb:
    image: mariadb
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager, node.hostname == lightsail1]
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: with-kid
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    networks:
      - overlay

  redis:
    image: redis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager, node.hostname == lightsail1]
      restart_policy:
        condition: on-failure
    ports:
      - "3679:3679"
    volumes:
      - /opt/redis/data:/data
    networks:
      - overlay

  nginx:
    image: minudev1212/withkid-webserver:0.4
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager, node.hostname == lightsail1]
      restart_policy:
        condition: on-failure
    ports:
      - "37772:800"
      - "80:80"
      - "8090:8090"
    volumes:
      - /usr/share/nginx/imgFolder:/usr/share/nginx/imgFolder
      - /usr/share/nginx/spa-mat:/usr/share/nginx/spa-mat
      - /var/www/withkid:/var/www/withkid
    networks:
      - overlay

networks:
  overlay:
    external: false
