version: "3"

services:

  resource_server:
    image: minudev1212/withkid-resource-server:0.6.3
    deploy:
      replicas: 1
      resources: 
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    depends_on:
      - rdb
      - redis
    ports: 
      - "8081:8081"
    networks:
      - overlay
  auth_server:
    image: minudev1212/withkid-auth-server:0.4.2
    deploy:
      replicas: 1
      resources: 
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    depends_on:
      - rdb
    ports: 
      - "8090:8082"
    networks:
      - overlay

  rdb:
    image: mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: with-kid
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    networks:
      - overlay  

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3679:3679"
    volumes:
      - /opt/redis/data:/data
    networks: 
      - overlay

  nginx:
    image: minudev1212/withkid-webserver:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "37772:80"
    volumes:
      - /usr/share/nginx:/usr/share/nginx/imgFolder
    networks: 
      - overlay

networks:
  overlay: 
    external: false
