version: '3'

services:

  rdb:
    image: mariadb
    # container_name: withkid-rd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: with-kid
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    networks:
      - withkid-bridge  

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # container_name: withkid-redis
    ports:
      - "3679:3679"
    volumes:
      - /opt/redis/data:/data
    networks: 
      - withkid-bridge

  nginx:
    image: minudev1212/withkid-webserver:0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "37772:80"
    volumes:
      - /usr/share/nginx:/usr/share/nginx/imgFolder
    networks: 
      - withkid-bridge
networks:
  withkid-bridge: 
    external: true
